config/routes.rb
Coolshop::Application.routes.draw do
  root to: 'products#index'

  resources :products
  resources :orders do
    post :add_product, on: :collection
  end
  resources :order_products
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :order_products

  attr_accessible :comment, :email, :name, :phonenumber, :order_products_attributes

  accepts_nested_attributes_for :order_products

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
            :length   => { :maximum => 50 }

  validates :email, :presence => true,
            :format   => { :with => email_regex }

  validates :phonenumber, :presence => true

  def items_from_product_ids(wanted_products)
    wanted_products.present? && wanted_products.keys.each do |product_id|
      self.order_products.build(product_id: product_id, quantity: wanted_products[product_id])
    end
  end

end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  attr_accessible :product_id, :quantity

  belongs_to :product
  belongs_to :order

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :category_id

  belongs_to :category
  belongs_to :quantity

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.find(params[:id])
    @products = @categories.products.paginate(page: params[:page], per_page: 6)
  end
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  def index
    session[:products] = {} unless session[:products]
    @items = Product.where(id: session[:products].keys)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
    @order.items_from_product_ids session[:products]
  end

  def create
    @order = Order.new(params[:order])
    if @order.save
      session[:products] = {}
      redirect_to new_order_path, notice: t('notices.success_order')
    else
      render "new"
    end
  end

  def add_product
    session[:products] = {} unless session[:products]
    if session[:products][params[:product_id].to_i]
      session[:products][params[:product_id].to_i]+= 1
    else
      session[:products][params[:product_id].to_i] = 1
    end
    render json: :ok
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.paginate(:page => params[:page], per_page: 6)
    session[:products] = {} unless session[:products]
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories_menu
    links = Category.all.map do |category|
      content_tag :li do
        link_to "Price: #{category.name}$", category
      end
    end

      raw(links.join("\n"))
  end
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/show.html.haml
%h3{style: "text-align: center"} Товары
= will_paginate @products
%ul.block-grid.two-up
  = render @products
= will_paginate @products

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title CoolShop
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row
      .twelve.columns
        %h3{style: "text-align: center"} Куча одинаковой херни по 999 баксов! Добро пожаловать!
        - if notice
          .alert-box.success{style: "text-align: center"}= notice
        - if alert
          .alert-box.alert{style: "text-align: center"}= notice
        .row
          .three.columns
            %div{style: "text-align: center"}
              %h6категории:
              %ul
                %li= link_to "All prices", root_path
                = categories_menu
          .seven.columns
            = yield
          .two.columns
            %div{style: "text-align: center"}
              = link_to 'Ваша Корзина', order_products_path, class: 'small success radius button'
%ul{style: "text-align: center"}
  #myModal.reveal-modal
    %h2 Товар добавлен!

app/views/order_products/index.html.haml
.panel
  %table{ style: "width: 100%;" }
    %thead
      %tr
        %td= "Название товара"
        %td= "Кол-во"
        %td= "Цена"
        %td= "Сумма ($)"
    %tbody
      - @items.each do |p|
        %tr
          %td= p.name
          %td= session[:products][p.id]
          %td= p.price
          %td= p.price*session[:products][p.id]
.div{style: "text-align: center"}
  = link_to 'Оформить Покупку', new_order_path, class: 'small button'
  = link_to 'Вернуться к Просмотру Продуктов', root_path, class: "small button"

app/views/orders/new.html.haml
%h4{ style: "text-align: center;" } Ваш заказ
= simple_form_for @order do |f|
  %table{ style: "width: 100%;" }
    %thead
      %tr
        %td= "Название товара"
        %td= "Цена"
        %td.two= "Кол-во"
    %tbody
      = f.simple_fields_for :order_products do |op|
        = op.input :product_id, as: :hidden
        %tr
          %td= op.object.product.name
          %td= op.object.product.price
          %td= op.input :quantity, input_html: { maxlength: 3 }, label: false
    %tfoot
      %tr
        %td{ colspan: 2, style: "text-align: right;" }= "Итого: #{f.object.order_products.map{ |op| op.quantity * op.product.price }.reduce(:+)}$"
  %h4{ style: "text-align: center;" } Ваши данные
  .panel
    %ul
      = f.input :name, label: "Имя"
      = f.input :email, label: "Email", placeholder: "user@domain.com"
      = f.input :phonenumber, label: "Номер телефона"
      = f.input :comment, label: "Ваш комментарий"
  .row{style: "text-align: center;"}
    = f.button :submit, class: "small button", value: "Отправить заказ"
    = link_to 'Вернуться к Просмотру Товаров', root_path, class: "small radius button"

app/views/products/_product.html.haml
%li
  .product{ data: { product_id: product.id } }
    %ul{style: "text-align: center"}
      -img= image_tag( asset_path("#{product.category.name}""/#{product.id}" "/1.jpeg"), alt: product.name )
      = link_to img, product
      %li
        %b Name:
        = product.name
      %li
        %b Price:
        = product.price
        $
      = link_to 'Подробнее', product, class: 'small button radius'
      - if session[:products][product.id].present? && session[:products][product.id] >> 0
        = link_to "В Корзине", '#', class: 'small success button radius add_to_cart', "data-reveal-id" => "myModal"
      - else
        = link_to 'В Корзину', '#', class: 'small button radius add_to_cart', data: { "reveal-id" => "myModal" }

app/views/products/index.html.haml
%h3{style: "text-align: center"} Товары
= will_paginate
%ul.block-grid.two-up
  = render @products
= will_paginate

app/views/products/show.html.haml
.six.columns
  %h5{style: "text-align: center"}= "Подробнее о: #{@product.name}"
  #featured
    %img{src: asset_path("#{@product.category.name}/#{@product.id}/1.jpeg"), alt: @product.name}/
    %img{src: asset_path("#{@product.category.name}/#{@product.id}/2.jpeg"), alt: @product.name}/
.six.columns
  .product{ data: { product_id: @product.id } }
    %ul
      %li= "Name: #{@product.name}"
      %li= "Description: #{@product.description}"
      %li= "Price: #{@product.price}"
      = link_to 'Добавить в Корзину', '#', class: 'small radius button add_to_cart'
  = link_to 'Вернуться к Просмотру Товаров', root_path, class: "small radius button"

:javascript
  $(window).load(function() {
      $('#featured').orbit();
  });